### PR TITLE
Add Mountpoint functionality 

### PR DESCRIPTION
**Pull request by f-hrtmnn**
To specify your approle mount point, the parameter mount_point was added to:

- vaultlocker.conf
- _vault_client function in vaultlocker/shell.py

### CODE REVIEW

**Comment by flix444** [comment]
+1 pls apply the request! 
@wolsen

**Comment by rnsc** [comment]
@devhopsde can you update your PR to remove the conflict and make the build pass?
maybe the mount_point should also have a default value?

**Comment by wolsen** [comment]
This looks like a sane change to me - can you rebase it?

**Comment by rnsc** [comment]
@devhopsde @wolsen @flix444 FYI, I have added that functionality in this PR: https://github.com/openstack-charmers/vaultlocker/pull/19

**Comment by f-hrtmnn** [comment]
@rnsc Thanks :)

**Pull request closed without merging**
